export const FETCH_ALL = 'FETCH_ALL'
export const FETCH_BY_ID = 'FETCH_BY_ID'
export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH'
